### ISSUE TITLE
It yaml sorted by this package?

### ISSUE THREAD

**Issue by gustawdaniel** [osimek1/intellij-code-blocks-sorter#14]

**Comment by osimek1** [comment]
Yes it is, it is language independent - I have use it with yaml, json, javascript, typescript, coffeescritp, php, Java.

As you can see there are some small issues  but at the moment I have no time to maintanace it, I hope that I'll take care of it soon. 

Why are you asking? Have you found some bug?

**Comment by gustawdaniel** [comment]
Not bug. I did not tested it before asking. I was considering scenario:

```
a: 
  d: "value"
  c: "value"
b: 
  e: "value"
```

And wanted to obtain

```
a: 
  c: "value"
  d: "value"
b: 
  e: "value"
```

Simple sorting lines should give

```
a: 
b: 
  c: "value"
  d: "value"
  e: "value"
```

and this is not valid JSON. I didn't know that this package is smart enough, because docs not specyfi that `yaml` is sorted correctly.
